module.exports = {
	MOD_SUICIDE: 'MOD_SUICIDE',
	MOD_FALLING: 'MOD_FALLING',
	MOD_CRUSH: 'MOD_CRUSH',
	MOD_WATER: 'MOD_WATER',
	MOD_SLIME: 'MOD_SLIME',
	MOD_LAVA: 'MOD_LAVA',
	MOD_TARGET_LASER: 'MOD_TARGET_LASER',
	MOD_TRIGGER_HURT: 'MOD_TRIGGER_HURT'
};
